---
title: 'Assignment 4: Lobster Abundance'
author: "Indigo Bannister & Gavriella Keyles"
date: "11/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r}
# Attach packages
library(tidyverse)
library(tidyr)
library(here)
library(janitor)
library(ggridges)
library(viridis)
library(plotly)

# Read in data file: lobster_abundance_sbc_lter.csv

lobster_abun <- read_csv(here("raw_data","lobster_abundance_sbc_lter.csv"),
                         na = "-99999")
```

```{r}


lobster_clean <- lobster_abun %>% 
  clean_names() %>% 
  tidyr::uncount(count)


# Part A
lobster_a <- lobster_clean %>% 
  select(year, site) %>% 
  count(year, site) %>% 
  rename(annual_total = n)

graph_a <- ggplot(lobster_a, aes(x = year, y = annual_total, group = site, color = site)) +
  geom_line() +
  theme_minimal() +
  scale_color_viridis (discrete = TRUE) +
  labs(
    x = "Year",
    y = "Total annual lobsters counted",
    title = "Year-over-year lobster count change, 
    Santa Barbara County"
  )
  
ggplotly(graph_a)
  
```

```{r}
# Part B
lobster_2018 <- lobster_clean %>% 
  select(year, size_mm, site) %>% 
  filter(year %in% c(2018))

lobster_2012 <- lobster_clean %>% 
  select(year, size_mm, site) %>% 
  filter(year %in% c(2012))

graph_b <- ggplot() +
  geom_density_ridges(data = lobster_2018, aes(x = size_mm, y = site)) +
  geom_density_ridges(data = lobster_2012, aes(x = size_mm, y = site))

graph_b

```

